
import "./globals.css";

import {JetBrains_Mono} from 'next/font/google'

//components
import Header from "@/components/Header/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";



const jetBrainsMono= JetBrains_Mono({
    substs: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    preload: false,
    variable: '--font-jetBrainsMono'
})


export const metadata = {
  title: "Mamun Ahmed - Front-end Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetBrainsMono.variable}
      >
        <Header />
        <StairTransition/>
        <PageTransition>

        {children}
        </PageTransition>
      </body>
    </html>
  );
}
